#!/bin/bash
# Restart AlternateImage
# by chris1111
# Restart AlternateImage
if [ -d "/Applications/OpenCore Créateur.app" ]; then
  killall -c "OpenCore Créateur" && sleep 0.2 && open /Applications/"OpenCore Créateur.app"
fi


