#!/bin/bash
# Restart AlternateImage
# by chris1111
# Restart AlternateImage
if [ -d "/Applications/OpenCore Creator.app" ]; then
  killall -c "OpenCore Creator" && sleep 0.2 && open /Applications/"OpenCore Creator.app"
fi



