#!/bin/bash
# script OpenCore-Creator
# http://hackintosh-montreal.com
# (c) Copyright 2019 2025 chris1111 
# Vars
# Set Icon directory and file 
iconfile="/System/Library/CoreServices/Finder.app/Contents/Resources/Finder.icns"
apptitle="OpenCore Creator"
version="1.0"

PARENTDIR=$(dirname "$0")
cd "$PARENTDIR"
#   Slick Progress Bar
sleep 1 & PID=$! #Progress Bar

echo "`tput setaf 7``tput sgr0``tput bold``tput setaf 26`
                **************************************************** 
                *************     OpenCore Creator    ************** 
                ****************************************************
`tput sgr0` `tput setaf 7``tput sgr0`"
echo " "
echo " "
printf "["
# While process is running...
while kill -0 $PID 2> /dev/null; do 
    printf  "♾🔨♾🔨♾🔨♾🔨"
    sleep 0.2
done

printf '\e[8;47;82t'

nameh=`users`
function echob() {
  echo "`tput bold`$1`tput sgr0`"
}
function head
{
clear
echo "              = = = = = = = = = = = = = = = = = = = = = = = = =  "

tput blink                    
echo "                        Installer OpenCore Creator" 
tput sgr0

echo "              = = = = = = = = = = = = = = = = = = = = = = = = =  "
}
function menu
{
echo "                Welcome  $nameh, Installer OpenCore Creator"
echo " "
echo "                       `tput setaf 26`
                         Credit OpenCore Team
                         Credit Apple"
echo " "
echo "                        
                 `tput setaf 7``tput sgr0``tput bold``tput setaf 26`Type: ⬇`tput sgr0` `tput setaf 7``tput sgr0`︎"
echo "               =========================================== "
echo "                     ✅  0 = `tput setaf 7``tput sgr0``tput bold``tput setaf 26`Check OpenCore version`tput sgr0` `tput setaf 7``tput sgr0`"
echo "               =========================================== "
echo "                     ✅  1 = `tput setaf 7``tput sgr0``tput bold``tput setaf 26`Build OpenCore`tput sgr0` `tput setaf 7``tput sgr0`"
echo "               =========================================== "
echo "                     ✅  2 = `tput setaf 7``tput sgr0``tput bold``tput setaf 26`Check update OpenCore`tput sgr0` `tput setaf 7``tput sgr0`"
echo "               =========================================== "
echo "                     ✅  3 = `tput setaf 7``tput sgr0``tput bold``tput setaf 26`Update OpenCore`tput sgr0` `tput setaf 7``tput sgr0`"
echo "               =========================================== "
echo "                     ✅  4 = `tput setaf 7``tput sgr0``tput bold``tput setaf 26`Build Kexts OpenCore`tput sgr0` `tput setaf 7``tput sgr0`"
echo "               =========================================== "
echo "                     ✅  5 = `tput setaf 7``tput sgr0``tput bold``tput setaf 26`Manuel references OpenCore`tput sgr0` `tput setaf 7``tput sgr0`"
echo "               =========================================== "
echo "                     ✅  P = `tput setaf 7``tput sgr0``tput bold``tput setaf 26`Terminal Profile`tput sgr0` `tput setaf 7``tput sgr0`"  
echo "               =========================================== "
echo "                     ✅  V = `tput setaf 7``tput sgr0``tput bold``tput setaf 26`View Commits OpenCore`tput sgr0` `tput setaf 7``tput sgr0`"  
echo "               =========================================== "
echo "                     ❎  X = `tput setaf 7``tput sgr0``tput bold``tput setaf 26`Quit (Exit)`tput sgr0` `tput setaf 7``tput sgr0`" 
echo "               =========================================== "

echo "              = = = = = = = = = = = = = = = = = = = = = = = = =  "

tput blink                    
echo "                         Installer OpenCore Creator" 
tput sgr0

echo "              = = = = = = = = = = = = = = = = = = = = = = = = =  "


read -n 1 option
}
function OPENCOREV
{
head
echo " "
echo "Check OpenCore version"
Sleep 1
echo "= = = = = = = = = = = = = = = = = = = = = = = = =  
OpenCore"

grep OPEN_CORE_VERSION $HOME/Github/OpenCorePkg/Include/Acidanthera/Library/OcMainLib.h | sed 's/.*"\(.*\)".*/\1/' | grep -E '^[0-9.]+$'
echo "= = = = = = = = = = = = = = = = = = = = = = = = =  "

echo "`tput setaf 7``tput sgr0``tput bold``tput setaf 26`Check OpenCore version.`tput sgr0` `tput setaf 7``tput sgr0`"
echo " "
}
function OPENCORE
{
head
echo " "
response=$(osascript -e 'tell app "System Events" to display dialog "
Welcome to OpenCore Creator
This program allows you to build OpenCore.
You need Xcode and the Command Line Tools installed.
The output folder will be in
➤ $HOME/Github/OpenCorePkg

Works from macOS Big Sur 11 to macOS Tahoe 26

\n\nCancel Quit" buttons {"Cancel","OpenCore"} default button 2 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'"  ')

answer=$(echo $response | grep "OpenCore")

# Cancel is user does not select OpenCore
if [ ! "$answer" ] ; then
  osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
echo "              = = = = = = = = = = = = = = = = = = = = = = = = =  "

tput blink                    
echo "                      User Cancel OpenCore Creator" 
tput sgr0

echo "              = = = = = = = = = = = = = = = = = = = = = = = = =  "
  exit 0
fi

echo "Build OpenCore"
Sleep 4
file="/usr/local/bin/"
if [[ -f $file/nasm && -f $file/ndisasm && -f $file/iasl && -f $file/mtoc ]]; then
 echo "Binary files exists ! Build OpenCore"
 Sleep 3
else
 echo "Some binary files are missing"
echo "
=======================================
Some binary files are missing! 🚫
OpenCore-Creator must download and install the missing binaries.
Building the kexts must be performed as root.
Type your password:
======================================= "
sudo mkdir -p /usr/local/bin
pushd /Private/tmp >/dev/null || exit 1
BIN=BIN-Exctract
rm -rf /Private/tmp/BIN-Exctract
mkdir -p $BIN
# mtoc
curl -OL "https://github.com/acidanthera/ocmtoc/releases/download/1.0.3/ocmtoc-1.0.3-RELEASE.zip" || exit 1
# nasm
pushd /Private/tmp >/dev/null || exit 1
rm -rf nasm-mac64.zip
curl -OL "https://github.com/acidanthera/ocbuild/raw/master/external/nasm-mac64.zip" || exit 1
nasmzip=$(cat nasm-mac64.zip)
rm -rf nasm-*
curl -OL "https://github.com/acidanthera/ocbuild/raw/master/external/${nasmzip}" || exit 1
# iasl
pushd /Private/tmp >/dev/null || exit 1
rm -rf iasl-macosx.zip
curl -OL "https://github.com/acidanthera/ocbuild/raw/master/external/iasl-macosx.zip" || exit 1
iaslzip=$(cat iasl-macosx.zip)
rm -rf iasl-macosx.zip
curl -OL "https://github.com/acidanthera/ocbuild/raw/master/external/${iaslzip}" || exit 1
# unzip all
pushd /Private/tmp >/dev/null || exit 1
unzip -jo nasm-2.15.05-macosx.zip nasm-2.15.05/nasm -d $BIN
unzip -jo nasm-2.15.05-macosx.zip nasm-2.15.05/ndisasm -d $BIN
unzip -jo iasl-20200528-macosx.zip iasl -d $BIN
unzip -jo ocmtoc-1.0.3-RELEASE.zip mtoc -d $BIN
# remove zip
pushd /Private/tmp >/dev/null || exit 1
rm -rf *.zip
sudo cp -Rp $BIN/ndisasm /usr/local/bin
sudo cp -Rp $BIN/nasm /usr/local/bin
sudo cp -Rp $BIN/iasl /usr/local/bin
sudo cp -Rp $BIN/mtoc /usr/local/bin
echo "Build OpenCore ✅"
Sleep 3
fi

if [ "/$HOME/Github/OpenCorePkg" ]; then
	rm -rf "/$HOME/Github/OpenCorePkg"
fi

xcodebuild -version
sleep 1
echo "
Clone Build "
mkdir -p $HOME/Github
Sleep 1
cd $HOME/Github
Sleep 1
git clone https://github.com/acidanthera/OpenCorePkg.git
Sleep 1
echo "Build OpenCore Duet"
Sleep 1
cd $HOME/Github/OpenCorePkg
./build_duet.tool
Sleep 1
echo "Build OpenCore"
Sleep 1
cd $HOME/Github/OpenCorePkg
./build_oc.tool
Sleep 1
Open $HOME/Github/OpenCorePkg/Binaries
echo "======================================="
echo "Build OpenCore Done!  "
echo "======================================="
echo " "
}
function CHECKUPDATE
{
head
echo " "
echo "OpenCore Check-Update"
Sleep 3
echo "[ Fetch ⬇︎ ]"
cd ~/Github/OpenCorePkg
if [[ -d .git ]]; then
  git fetch --all
  git pull origin master
  Sleep 2
else
  echo "Error: This directory is not a Git repository. Unable to verify update!"
fi
echo " "
}
function UPDATE
{
head
echo " "
echo "OpenCore Update"
Sleep 2
echo "[Git Pull OpenCorePkg ⬇︎ ]"
cd ~/Github/OpenCorePkg
if [[ -d .git ]]; then
  git fetch --all
  git pull origin master
rm -rf $HOME/Github/OpenCorePkg/Binaries/*.zip
Sleep 1
echo "Build OpenCore Duet"
Sleep 2
OLD="(X64 IA32)"
MYPATH="$HOME/Github/OpenCorePkg/build_duet.tool"
TFILE="/Private/tmp/out.tmp"
for f in $MYPATH
do
  if [ -f $f -a -r $f ]; then
   echo "Setup OC duet build ARCHS=X64"
   sed "s/$OLD/(X64)/g" "$f" > $TFILE && mv $TFILE "$f"
   Sleep 1
   chmod 755 $HOME/Github/OpenCorePkg/build_duet.tool
  else
   echo "Error: Cannot read $f"
  fi
done
Sleep 1
cd $HOME/Github/OpenCorePkg
./build_duet.tool
Sleep 1
echo "Build OpenCore"
Sleep 2
OLD="(X64 IA32)"
MYPATH="$HOME/Github/OpenCorePkg/build_oc.tool"
TFILE="/Private/tmp/out.tmp"
for f in $MYPATH
do
  if [ -f $f -a -r $f ]; then
   echo "Setup OC build ARCHS=X64"
   sed "s/$OLD/(X64)/g" "$f" > $TFILE && mv $TFILE "$f"
   Sleep 1
   chmod 755 $HOME/Github/OpenCorePkg/build_oc.tool
  else
   echo "Error: Cannot read $f"
  fi
done
Sleep 1
cd $HOME/Github/OpenCorePkg
./build_oc.tool
Sleep 1
else
  echo "Error: This directory is not a Git repository. Unable to verify update!"
fi
Open $HOME/Github/OpenCorePkg/Binaries
echo "======================================="
echo "Update OpenCore Done!  "
echo "======================================="
echo " "
}
function KEXTS
{
head
echo " "
response=$(osascript -e 'tell app "System Events" to display dialog "
Welcome to OpenCore Creator
This program allows you to build kexts for OpenCore.
You need Xcode and the Command Line Tool installed.
The output folder will be in
➤ $HOME/Github/Build-Kexts

Works from macOS Big Sur 11 to macOS Tahoe 26

\n\nCancel Quit" buttons {"Cancel","OpenCore Kexts"} default button 2 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'"  ')

answer=$(echo $response | grep "OpenCore Kexts")

# Cancel is user does not select OpenCore Kexts
if [ ! "$answer" ] ; then
  osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
echo "              = = = = = = = = = = = = = = = = = = = = = = = = =  "

tput blink                    
echo "                      User Cancel OpenCore Creator" 
tput sgr0

echo "              = = = = = = = = = = = = = = = = = = = = = = = = =  "
  exit 0
fi

echo "Build Kexts"
Sleep 4
file="/usr/local/bin/"
if [[ -f $file/nasm && -f $file/ndisasm && -f $file/iasl && -f $file/mtoc ]]; then
 echo "Binary files exists ! Build Kexts"
 Sleep 3
else
 echo "Some binary files are missing"
echo "
=======================================
Some binary files are missing! 🚫
OpenCore-Creator must download and install the missing binaries.
Building the kexts must be performed as root.
Type your password:
======================================= "
sudo mkdir -p /usr/local/bin
pushd /Private/tmp >/dev/null || exit 1
BIN=BIN-Exctract
rm -rf /Private/tmp/BIN-Exctract
mkdir -p $BIN
# mtoc
curl -OL "https://github.com/acidanthera/ocmtoc/releases/download/1.0.3/ocmtoc-1.0.3-RELEASE.zip" || exit 1
# nasm
pushd /Private/tmp >/dev/null || exit 1
rm -rf nasm-mac64.zip
curl -OL "https://github.com/acidanthera/ocbuild/raw/master/external/nasm-mac64.zip" || exit 1
nasmzip=$(cat nasm-mac64.zip)
rm -rf nasm-*
curl -OL "https://github.com/acidanthera/ocbuild/raw/master/external/${nasmzip}" || exit 1
# iasl
pushd /Private/tmp >/dev/null || exit 1
rm -rf iasl-macosx.zip
curl -OL "https://github.com/acidanthera/ocbuild/raw/master/external/iasl-macosx.zip" || exit 1
iaslzip=$(cat iasl-macosx.zip)
rm -rf iasl-macosx.zip
curl -OL "https://github.com/acidanthera/ocbuild/raw/master/external/${iaslzip}" || exit 1
# unzip all
pushd /Private/tmp >/dev/null || exit 1
unzip -jo nasm-2.15.05-macosx.zip nasm-2.15.05/nasm -d $BIN
unzip -jo nasm-2.15.05-macosx.zip nasm-2.15.05/ndisasm -d $BIN
unzip -jo iasl-20200528-macosx.zip iasl -d $BIN
unzip -jo ocmtoc-1.0.3-RELEASE.zip mtoc -d $BIN
# remove zip
pushd /Private/tmp >/dev/null || exit 1
rm -rf *.zip
sudo cp -Rp $BIN/ndisasm /usr/local/bin
sudo cp -Rp $BIN/nasm /usr/local/bin
sudo cp -Rp $BIN/iasl /usr/local/bin
sudo cp -Rp $BIN/mtoc /usr/local/bin
echo "Build Kexts ✅"
Sleep 3
fi


echo "Build Kexts"

if [ "/$HOME/Github/Build-Kexts" ]; then
	rm -rf "/$HOME/Github/Build-Kexts"
fi


sleep 1
echo "
Clone Build "
mkdir -p $HOME/Github/Build-Kexts


cd $HOME/Github/Build-Kexts
git clone https://github.com/acidanthera/MacKernelSDK
git clone https://github.com/acidanthera/VirtualSMC.git
git clone https://github.com/acidanthera/Lilu.git
git clone https://github.com/acidanthera/AppleALC.git 
git clone https://github.com/acidanthera/WhateverGreen.git
git clone https://github.com/acidanthera/AirportBrcmFixup.git
git clone https://github.com/acidanthera/NVMeFix.git
git clone https://github.com/acidanthera/BrightnessKeys.git
git clone https://github.com/acidanthera/IntelMausi.git
git clone https://github.com/acidanthera/BrcmPatchRAM.git
git clone https://github.com/acidanthera/VoodooPS2.git
git clone https://github.com/acidanthera/RestrictEvents.git
git clone https://github.com/0xFireWolf/RealtekCardReader.git
git clone https://github.com/0xFireWolf/RealtekCardReaderFriend.git
git clone https://github.com/acidanthera/CryptexFixup.git
cp -r ./MacKernelSDK ./Lilu

echo "
Build Lilu Debug " 
Sleep 3 
xcodebuild -project $HOME/Github/Build-Kexts/Lilu/Lilu.xcodeproj -configuration Debug ARCHS=x86_64 ONLY_ACTIVE_ARCH=YES CONFIGURATION_BUILD_DIR=$HOME/Github/Build-Kexts
Sleep 1
cp -r $HOME/Github/Build-Kexts/Lilu.kext $HOME/Github/Build-Kexts/WhateverGreen
cp -r ./MacKernelSDK ./WhateverGreen
cp -r $HOME/Github/Build-Kexts/Lilu.kext $HOME/Github/Build-Kexts/AirportBrcmFixup
cp -r ./MacKernelSDK ./AirportBrcmFixup
cp -r $HOME/Github/Build-Kexts/Lilu.kext $HOME/Github/Build-Kexts/IntelMausi
cp -r ./MacKernelSDK ./IntelMausi
cp -r $HOME/Github/Build-Kexts/Lilu.kext $HOME/Github/Build-Kexts/BrcmPatchRAM
cp -r ./MacKernelSDK ./BrcmPatchRAM
cp -r $HOME/Github/Build-Kexts/Lilu.kext $HOME/Github/Build-Kexts/NVMeFix
cp -r ./MacKernelSDK ./NVMeFix
cp -r $HOME/Github/Build-Kexts/Lilu.kext $HOME/Github/Build-Kexts/BrightnessKeys
cp -r ./MacKernelSDK ./BrightnessKeys
cp -r $HOME/Github/Build-Kexts/Lilu.kext $HOME/Github/Build-Kexts/VoodooPS2
cp -r ./MacKernelSDK ./VoodooPS2
cp -r $HOME/Github/Build-Kexts/Lilu.kext $HOME/Github/Build-Kexts/RestrictEvents
cp -r ./MacKernelSDK ./RestrictEvents
cp -r $HOME/Github/Build-Kexts/Lilu.kext $HOME/Github/Build-Kexts/RealtekCardReader
cp -r ./MacKernelSDK ./RealtekCardReader
cp -r $HOME/Github/Build-Kexts/Lilu.kext $HOME/Github/Build-Kexts/RealtekCardReaderFriend
cp -r ./MacKernelSDK ./RealtekCardReaderFriend
cp -r $HOME/Github/Build-Kexts/Lilu.kext $HOME/Github/Build-Kexts/VirtualSMC
cp -r ./MacKernelSDK ./VirtualSMC
cp -r $HOME/Github/Build-Kexts/Lilu.kext $HOME/Github/Build-Kexts/AppleALC
cp -r ./MacKernelSDK ./AppleALC
cp -r $HOME/Github/Build-Kexts/Lilu.kext $HOME/Github/Build-Kexts/CryptexFixup
cp -r ./MacKernelSDK ./CryptexFixup

sleep 2
mkdir -p $HOME/Github/Build-Kexts/Build
echo "
Build WhateverGreen " 
xcodebuild -project $HOME/Github/Build-Kexts/WhateverGreen/WhateverGreen.xcodeproj -alltargets -configuration Release
Sleep 2
echo "
Build AirportBrcmFixup " 
xcodebuild -project $HOME/Github/Build-Kexts/AirportBrcmFixup/AirportBrcmFixup.xcodeproj -alltargets -configuration Release
Sleep 2
echo "
Build IntelMausi " 
xcodebuild -project $HOME/Github/Build-Kexts/IntelMausi/IntelMausiEthernet.xcodeproj -alltargets -configuration Release
Sleep 2
echo "
Build BrcmPatchRAM " 
xcodebuild -project $HOME/Github/Build-Kexts/BrcmPatchRAM/BrcmPatchRAM.xcodeproj -alltargets -configuration Release
Sleep 2
echo "
Build NVMeFix " 
xcodebuild -project $HOME/Github/Build-Kexts/NVMeFix/NVMeFix.xcodeproj -alltargets -configuration Release
Sleep 2
echo "
Build BrightnessKeys " 
xcodebuild -project $HOME/Github/Build-Kexts/BrightnessKeys/BrightnessKeys.xcodeproj -alltargets -configuration Release
Sleep 2
echo "
Build RestrictEvents "
xcodebuild -project $HOME/Github/Build-Kexts/RestrictEvents/RestrictEvents.xcodeproj -alltargets -configuration Release
Sleep 2
echo "
Build VoodooPS2 " 
xcodebuild -project $HOME/Github/Build-Kexts/VoodooPS2/VoodooPS2Controller.xcodeproj -alltargets -configuration Release
Sleep 2
echo "
Build CryptexFixup " 
xcodebuild -project $HOME/Github/Build-Kexts/CryptexFixup/CryptexFixup.xcodeproj -alltargets -configuration Release
Sleep 2
echo "
Build Lilu Release "
Sleep 2
xcodebuild -project $HOME/Github/Build-Kexts/Lilu/Lilu.xcodeproj -alltargets -configuration Release
echo "
Build RealtekCardReader "
Sleep 2
xcodebuild -project $HOME/Github/Build-Kexts/RealtekCardReader/RealtekCardReader.xcodeproj -alltargets -configuration Release
echo "
Build RealtekCardReaderFriend "
Sleep 2
xcodebuild -project $HOME/Github/Build-Kexts/RealtekCardReaderFriend/RealtekCardReaderFriend.xcodeproj -alltargets -configuration Release
echo "
Build VirtualSMC "
Sleep 2
xcodebuild -project $HOME/Github/Build-Kexts/VirtualSMC/VirtualSMC.xcodeproj -configuration Release ARCHS=x86_64 ONLY_ACTIVE_ARCH=YES CONFIGURATION_BUILD_DIR=$HOME/Github/Build-Kexts/VirtualSMC
mkdir -p $HOME/Github/Build-Kexts/VirtualSMC/OUT
Sleep 1
tar xf $HOME/Github/Build-Kexts/VirtualSMC/VirtualSMC-*-RELEASE.zip --directory $HOME/Github/Build-Kexts/VirtualSMC/OUT
echo "
Build AppleALC
Please wait! Build AppleALC is taking a long time. . ."
Sleep 3
xcodebuild -project $HOME/Github/Build-Kexts/AppleALC/AppleALC.xcodeproj -alltargets -configuration Release
Sleep 2
rm -rf $HOME/Github/Build-Kexts/AirportBrcmFixup/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/AppleALC/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/BrcmPatchRAM/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/BrightnessKeys/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/IntelMausi/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/Lilu/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/NVMeFix/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/RestrictEvents/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/VirtualSMC/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/VoodooPS2/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/CryptexFixup/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/WhateverGreen/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/RealtekCardReader/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/RealtekCardReaderFriend/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/Lilu.kext
rm -rf $HOME/Github/Build-Kexts/*.zip
rm -rf $HOME/Github/Build-Kexts/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/AirportBrcmFixup/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/AppleALC/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/BrcmPatchRAM/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/BrightnessKeys/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/IntelMausi/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/Lilu/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/NVMeFix/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/RestrictEvents/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/VirtualSMC/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/VoodooPS2/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/CryptexFixup/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/WhateverGreen/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/RealtekCardReader/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/RealtekCardReaderFriend/MacKernelSDK
rm -rf $HOME/Github/Build-Kexts/MacKernelSDK
echo "Créatation Build finale "
Sleep 2
cp -r $HOME/Github/Build-Kexts/VirtualSMC/OUT/dSYM/* $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/VirtualSMC/OUT/Kexts/* $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/VirtualSMC/OUT/Tools/ $HOME/Github/Build-Kexts/Build/Tools
cp -r $HOME/Github/Build-Kexts/VirtualSMC/VirtualSMC-*-RELEASE.zip $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/AirportBrcmFixup/build/Release/* $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/AppleALC/build/Release/* $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/BrcmPatchRAM/build/Products/Release/* $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/BrightnessKeys/build/Release/* $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/IntelMausi/build/Release/* $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/Lilu/build/Release/* $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/RealtekCardReader/build/Release/* $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/RealtekCardReaderFriend/build/Release/* $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/NVMeFix/build/Release/* $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/RestrictEvents/build/Release/* $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/CryptexFixup/build/Release/* $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/VoodooPS2/build/Products/Release/dSYM/* $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/VoodooPS2/build/Products/Release/*.zip $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/VoodooPS2/build/Products/Release/*.kext $HOME/Github/Build-Kexts/Build
cp -r $HOME/Github/Build-Kexts/WhateverGreen/build/Release/* $HOME/Github/Build-Kexts/Build
cd $HOME/Github/Build-Kexts
ls | sort
find . -name '.DS_Store' -type f -delete

echo "======================================="
echo "Build Kexts Done!  "
echo "======================================="
Sleep 1
Open $HOME/Github/Build-Kexts/Build
echo " "
}
function MANUEL
{
head
echo " "
echo "Manuel OpenCore"
Sleep 1
Open $HOME/Github/OpenCorePkg/Docs/Configuration.pdf
echo " "
echo "`tput setaf 7``tput sgr0``tput bold``tput setaf 26`Manuel reference OpenCore.`tput sgr0` `tput setaf 7``tput sgr0`"
echo " "
}
function PROFILE
{
head
echo " "
echo "Terminal Profile"
Sleep 1

osascript <<EOD

set Term to choose from list {"Pro", "Homebrew", "Basic", "Grass", "Clear Dark", "Man Page", "Novel", "Ocean", "Red Sands", "Silver Aerogel", "Solid Colors"} with title "Setup Terminal Profiles" with prompt "Which profiles do you want to use?" default items "Pro" OK button name {"Profiles"} cancel button name {"Cancel"}


if Term is false then
	display dialog "Quit Terminal Profile" with icon note buttons {"Exit"} default button {"Exit"}
	error number -128
end if

if Term is {"Pro"} then
	do shell script "defaults write com.apple.terminal 'Default Window Settings' Pro"
	do shell script "defaults write com.apple.terminal 'Startup Window Settings' Pro"
	delay 1
	do shell script "killall Finder"
	
else if Term is {"Homebrew"} then
	do shell script "defaults write com.apple.terminal 'Default Window Settings' Homebrew"
	do shell script "defaults write com.apple.terminal 'Startup Window Settings' Homebrew"
	delay 1
	do shell script "killall Finder"
	
else if Term is {"Basic"} then
	do shell script "defaults write com.apple.terminal 'Default Window Settings' Basic"
	do shell script "defaults write com.apple.terminal 'Startup Window Settings' Basic"
	delay 1
	do shell script "killall Finder"
	
else if Term is {"Grass"} then
	do shell script "defaults write com.apple.terminal 'Default Window Settings' Grass"
	do shell script "defaults write com.apple.terminal 'Startup Window Settings' Grass"
	delay 1
	do shell script "killall Finder"
	
else if Term is {"Clear Dark"} then
	do shell script "defaults write com.apple.terminal 'Default Window Settings' 'Clear Dark'"
	do shell script "defaults write com.apple.terminal 'Startup Window Settings' 'Clear Dark'"
	delay 1
	do shell script "killall Finder"
	
else if Term is {"Man Page"} then
	do shell script "defaults write com.apple.terminal 'Default Window Settings' 'Man Page'"
	do shell script "defaults write com.apple.terminal 'Startup Window Settings' 'Man Page'"
	delay 1
	do shell script "killall Finder"
	
else if Term is {"Novel"} then
	do shell script "defaults write com.apple.terminal 'Default Window Settings' Novel"
	do shell script "defaults write com.apple.terminal 'Startup Window Settings' Novel"
	delay 1
	do shell script "killall Finder"
	
else if Term is {"Ocean"} then
	do shell script "defaults write com.apple.terminal 'Default Window Settings' Ocean"
	do shell script "defaults write com.apple.terminal 'Startup Window Settings' Ocean"
	delay 1
	do shell script "killall Finder"
	
else if Term is {"Red Sands"} then
	do shell script "defaults write com.apple.terminal 'Default Window Settings' 'Red Sands'"
	do shell script "defaults write com.apple.terminal 'Startup Window Settings' 'Red Sands'"
	delay 1
	do shell script "killall Finder"
	
else if Term is {"Silver Aerogel"} then
	do shell script "defaults write com.apple.terminal 'Default Window Settings' 'Silver Aerogel'"
	do shell script "defaults write com.apple.terminal 'Startup Window Settings' 'Silver Aerogel'"
	delay 1
	do shell script "killall Finder"
	
else if Term is {"Solid Colors"} then
	do shell script "defaults write com.apple.terminal 'Default Window Settings' 'Solid Colors'"
	do shell script "defaults write com.apple.terminal 'Startup Window Settings' 'Solid Colors'"
	delay 1
	do shell script "killall Finder"
	
end if



EOD

echo "`tput setaf 7``tput sgr0``tput bold``tput setaf 26`The Terminal Profile will be changed the next time you open OpenCore Creator.
Click Terminate to exit.`tput sgr0` `tput setaf 7``tput sgr0`"
Sleep 2

osascript -e 'tell application "Terminal" to quit'
echo " "
}
function COMMITS
{
head
echo " "
echo "Commits OpenCore"
Sleep 1
open 'https://github.com/acidanthera/OpenCorePkg/commits/master'
echo " "
echo "`tput setaf 7``tput sgr0``tput bold``tput setaf 26`View Commits OpenCore.`tput sgr0` `tput setaf 7``tput sgr0`"
echo " "
}
function Quit
{
clear
echo " "
echo "
Quit Installer OpenCore Creator"
osascript -e 'tell app "Terminal" to display dialog "
Quit OpenCore Creator" with icon file "System:Library:CoreServices:loginwindow.app:Contents:Resources:ShutDown.tiff" buttons {"Exit"} default button 1 with title " OpenCore Creator"'
echo " "
say thanks to using OpenCore Creator!
osascript -e 'display notification "" with title "Closing OpenCore Creator" subtitle "Thanks to using OpenCore Creator"'
echo " "



exit 123456

}
while [ 1 ]
do
head
menu
case $option in


0|0)
echo
OPENCOREV ;;
1|1)
echo
OPENCORE ;;
2|2)
echo
CHECKUPDATE ;;
3|3)
echo
UPDATE ;;
4|4)
echo
KEXTS ;;
5|5)
echo
MANUEL ;;
p|P)
echo
PROFILE ;;
v|V)
echo
COMMITS ;;
x|X)
echo
Quit ;;

*)
echo ""
esac
echo
echob "`tput setaf 7``tput sgr0``tput bold``tput setaf 26`Press a key to return to the menu`tput sgr0` `tput setaf 7``tput sgr0`"
echo
read -n 1 line
clear
done

exit
